version: "2"

services:
  conquest:

    # Use the prebuilt image or build from the source
    image: ghcr.io/aptvision/conquest
    #build: .

    ports:
    - 80:80
    environment:
      DB_TYPE: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_SERVER: "conquest"
      POSTGRES_USERNAME: "conquest"
      POSTGRES_PASSWORD: mysecretpassword
      AE_TITLE: CONQUESTSRV1
    depends_on:
      - postgres
    volumes:
    - /opt/conquest/data/

    # This is an example of how to mount custom lua scripts into the container, just
    # mounting is enough for them to be run.
    - ./lua-scripts:/opt/conquest/custom-lua-scripts/

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: "conquest"
      POSTGRES_PASSWORD: mysecretpassword
    ports:
    - 5432:5432
