version: "2.2"

services:
  conquest:
    build: .
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: "postgres"
      POSTGRES_HOST: "localhost:5436"
      POSTGRES_SERVER: "conquest"
      POSTGRES_USERNAME: "conquest"
      POSTGRES_PASSWORD: "conquest"
      AE_TITLE: CONQUESTSRV1
    volumes:
      - /opt/conquest/data/
      # This is an example of how to mount custom lua scripts into the container, just
      # mounting is enough for them to be run.
      - ./lua-scripts:/opt/conquest/custom-lua-scripts/
    network_mode: host
