{{ if .Values.ingress.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}-http"
  namespace: "{{ .Values.namespace }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "{{ .Values.name }}"
  sessionAffinity: None
status:
  loadBalancer: {}
{{ end }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}-dicom"
  namespace: "{{ .Values.namespace }}"
spec:
  {{ if eq .Values.network.dicomService.type "NodePort" }}
  type: NodePort
  ports:
    - name: dicom
      port: 5678
      protocol: TCP
      nodePort: {{ .Values.network.dicomService.nodePort }}
  {{ else }}
  type: ClusterIP
  ports:
    - name: dicom
      port: 5678
      protocol: TCP
      targetPort: 5678
  {{ end }}
  selector:
    app: "{{ .Values.name }}"
  sessionAffinity: None
status:
  loadBalancer: {}
