apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dicom
      port: 5678
      protocol: TCP
      targetPort: 5678
  selector:
    app: "{{ .Values.name }}"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
