name: Docker build and push

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aptvision/conquest

jobs:

  push:

    name: Docker build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          TAGS=""
          TIMESTAMP=$(date +%G%m%d%H%M)

          # Define the immutable tags, these contain the date and sha and will forever reference this exact commit
          if [[ $GITHUB_REF == refs/tags/* ]]; then
              TAGS=${DOCKER_IMAGE}:${GITHUB_REF#refs/tags/}-${TIMESTAMP}-${GITHUB_SHA:0:7}
          fi
          if [ "${{ github.event_name }}" = "pull_request" ]; then
              TAGS="$TAGS,${DOCKER_IMAGE}:${GITHUB_HEAD_REF}-${TIMESTAMP}-${GITHUB_SHA:0:7}"
          fi
          if [ "${{ github.event_name }}" = "push" ]; then
              TAGS="$TAGS,${DOCKER_IMAGE}:${GITHUB_REF##*/}-${TIMESTAMP}-${GITHUB_SHA:0:7}"
          fi

          # And some tags that are not immutable, the tag name can change which image it points to, these are convenience only
          TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          if [ "${{ github.event_name }}" = "schedule" ]; then
            TAGS=${DOCKER_IMAGE}:nightly
          fi

          echo "tags: ${TAGS}"

          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.prep.outputs.tags }}
          pull: true # To make sure we always pull new versions of upstream images
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
